package eu.anifantakis.lib.ksafe

/**
 * Result of an integrity token request.
 *
 * IMPORTANT: Tokens must be verified SERVER-SIDE with Google Play Integrity API
 * or Apple DeviceCheck API. Client-side verification is NOT secure.
 */
sealed class IntegrityResult {
    /**
     * Successfully obtained an integrity token.
     *
     * @param token The integrity token to send to your server for verification
     * @param platform The platform that generated this token ("android" or "ios")
     */
    data class Success(
        val token: String,
        val platform: String
    ) : IntegrityResult()

    /**
     * Failed to obtain an integrity token.
     *
     * @param message Human-readable error description
     * @param code Platform-specific error code (if available)
     */
    data class Error(
        val message: String,
        val code: Int? = null
    ) : IntegrityResult()

    /**
     * Integrity checking is not supported on this platform.
     * This is returned on JVM/Desktop and devices without Google Play Services.
     */
    data object NotSupported : IntegrityResult()
}

/**
 * Platform integrity verification using Google Play Integrity (Android)
 * and DeviceCheck (iOS).
 *
 * ## Purpose
 * This helper provides tokens for SERVER-SIDE verification of device integrity.
 * It does NOT perform client-side integrity checks (which would be insecure).
 *
 * ## Usage Flow
 * 1. Your app calls [requestIntegrityToken] with a server-generated nonce
 * 2. KSafe returns an [IntegrityResult.Success] with a token
 * 3. Your app sends the token to YOUR server
 * 4. Your server verifies the token with Google/Apple APIs
 * 5. Your server responds with pass/fail to your app
 *
 * ## Platform Requirements
 *
 * ### Android (Play Integrity)
 * - Google Play Services required
 * - Must set up Play Integrity API in Google Cloud Console
 * - Pass your Cloud Project Number when creating IntegrityChecker
 *
 * ### iOS (DeviceCheck)
 * - iOS 11+ required
 * - No additional setup needed for token generation
 * - Server needs Apple DeviceCheck API access for verification
 *
 * ### JVM/Desktop
 * - Not supported, always returns [IntegrityResult.NotSupported]
 *
 * ## Security Note
 * These APIs are designed to make bypassing harder, but determined attackers
 * with rooted/jailbroken devices and advanced tools may still succeed.
 * Use as one layer of defense, not the only protection.
 *
 * @see IntegrityResult
 */
expect class IntegrityChecker {
    /**
     * Check if integrity verification is available on this device.
     *
     * Returns false if:
     * - Platform doesn't support integrity checks (JVM)
     * - Google Play Services unavailable (Android)
     * - DeviceCheck unavailable (old iOS versions)
     */
    fun isAvailable(): Boolean

    /**
     * Request an integrity token for server-side verification.
     *
     * @param nonce A unique, unpredictable value to prevent replay attacks.
     *              Should be generated by your server and be at least 16 bytes.
     *              For Android, this will be hashed to create the request hash.
     *
     * @return [IntegrityResult.Success] with token on success,
     *         [IntegrityResult.Error] on failure,
     *         [IntegrityResult.NotSupported] if unavailable
     *
     * ## Example
     * ```kotlin
     * val checker = IntegrityChecker(context, cloudProjectNumber = 123456789L)
     * when (val result = checker.requestIntegrityToken(serverNonce)) {
     *     is IntegrityResult.Success -> {
     *         // Send result.token to your server for verification
     *         api.verifyIntegrity(result.token)
     *     }
     *     is IntegrityResult.Error -> {
     *         Log.e("Integrity", "Failed: ${result.message}")
     *     }
     *     is IntegrityResult.NotSupported -> {
     *         // Handle gracefully - maybe allow with reduced trust
     *     }
     * }
     * ```
     */
    suspend fun requestIntegrityToken(nonce: String): IntegrityResult
}
